{% set name = "remotezip" %}
{% set version = "0.12.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/remotezip-{{ version }}.tar.gz
  sha256: bf1ebe2be9f07a6e1c14d0e52ecffccd7a3e808dff4f9ba523c5e84d867a3fe3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  entry_points:
    - remotezip = remotezip:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - requests

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - remotezip --help
  imports:
    - remotezip

about:
  home: https://github.com/gtsystem/python-remotezip
  summary: Access zip file content hosted remotely without downloading the full file.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jhkennedy
