{% set name = "remotezip" %}
{% set version = "0.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/remotezip-{{ version }}.tar.gz
  sha256: ce65b7910c5c25d8950ed402023592967f5791ac14987141c050016ffad18dec

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python
    - pip
  run:
    - python
    - requests
    - tabulate

test:
  imports:
    - remotezip
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gtsystem/python-remotezip
  summary: Access zip file content hosted remotely without downloading the full file.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jhkennedy
