{% set name = "remotezip" %}
{% set version = "0.12.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/remotezip-{{ version }}.tar.gz
  sha256: 211ecf7dd291e5339359b3422ca758a679f3d89624f7cff6039e90a6904efd96

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - requests
    - tabulate

test:
  imports:
    - remotezip
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gtsystem/python-remotezip
  summary: Access zip file content hosted remotely without downloading the full file.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jhkennedy
